/**
 * Token Tamers v1 starter content pack.
 *
 * Sprite generation approach: all sprites in sprites.json are deterministically
 * generated by packages/content/tools/gen-sprites.ts using a seeded LCG keyed on
 * each sprite id. The script is committed alongside the output so sprites.json can
 * be regenerated at any time with `pnpm tsx packages/content/tools/gen-sprites.ts`.
 * TODO art pass: replace placeholder grids with hand-crafted sprites before release.
 *
 * JSON files are imported statically (resolveJsonModule: true) so the bundle
 * embeds all content — zero runtime file reads needed.
 */
import type {
  BattleRuleset,
  ContentPack,
  ModelRule,
  SpeciesDef,
  TraitDef,
  PatternDef,
  AchievementDef,
  HabitatDef,
  TrinketDef,
  SpriteDef,
} from '@token-tamers/core';

import modelsRaw from '../content/models.json' with { type: 'json' };
import speciesRaw from '../content/species.json' with { type: 'json' };
import traitsRaw from '../content/traits.json' with { type: 'json' };
import patternsRaw from '../content/patterns.json' with { type: 'json' };
import achievementsRaw from '../content/achievements.json' with { type: 'json' };
import habitatsRaw from '../content/habitats.json' with { type: 'json' };
import trinketsRaw from '../content/trinkets.json' with { type: 'json' };
import spritesRaw from '../content/sprites.json' with { type: 'json' };
import battleRaw from '../content/battle.json' with { type: 'json' };

const models = modelsRaw as ModelRule[];
const species = speciesRaw as SpeciesDef[];
const traits = traitsRaw as TraitDef[];
const patterns = patternsRaw as PatternDef[];
const achievements = achievementsRaw as AchievementDef[];
const habitats = habitatsRaw as HabitatDef[];
const trinkets = trinketsRaw as TrinketDef[];
const sprites = spritesRaw as SpriteDef[];
const battle = battleRaw as BattleRuleset;

export const contentPackV1: ContentPack = {
  schemaVersion: 1,
  // Season 0 — "Genesis": the five founding House lines (56 species). Each future
  // Season bumps this and ships its own obtainable roster (see docs/design).
  season: 0,
  models,
  species,
  traits,
  patterns,
  achievements,
  habitats,
  trinkets,
  sprites,
  // Live Dex denominator = Season 0's obtainable roster (the 56 base species).
  dexTotal: 56,
  // Home-House bias at hatch (cosmetic; invariant 3): 50% keep the model's House,
  // 50% spread across the other species-bearing Houses via the per-install salt.
  // Spreads single-model players (e.g. a whole org on one model) across Houses.
  houseBias: 0.5,
  // Battle tuning (design §11) — the circular House wheel + trait counters. All
  // content-tunable data; the engine reads it, never hardcodes it (invariant 9).
  battle,
};

export { validatePack } from './validate';
export { resolveHouse } from './models';
