/**
 * Token Tamers v1 starter content pack.
 *
 * Sprite generation approach: all sprites in sprites.json are deterministically
 * generated by packages/content/tools/gen-sprites.ts using a seeded LCG keyed on
 * each sprite id. The script is committed alongside the output so sprites.json can
 * be regenerated at any time with `pnpm tsx packages/content/tools/gen-sprites.ts`.
 * TODO art pass: replace placeholder grids with hand-crafted sprites before release.
 *
 * JSON files are imported statically (resolveJsonModule: true) so the bundle
 * embeds all content — zero runtime file reads needed.
 */
import type {
  ContentPack,
  ModelRule,
  SpeciesDef,
  TraitDef,
  PatternDef,
  AchievementDef,
  HabitatDef,
  TrinketDef,
  SpriteDef,
} from '@token-tamers/core';

import modelsRaw from '../content/v1/models.json' with { type: 'json' };
import speciesRaw from '../content/v1/species.json' with { type: 'json' };
import traitsRaw from '../content/v1/traits.json' with { type: 'json' };
import patternsRaw from '../content/v1/patterns.json' with { type: 'json' };
import achievementsRaw from '../content/v1/achievements.json' with { type: 'json' };
import habitatsRaw from '../content/v1/habitats.json' with { type: 'json' };
import trinketsRaw from '../content/v1/trinkets.json' with { type: 'json' };
import spritesRaw from '../content/v1/sprites.json' with { type: 'json' };

const models = modelsRaw as ModelRule[];
const species = speciesRaw as SpeciesDef[];
const traits = traitsRaw as TraitDef[];
const patterns = patternsRaw as PatternDef[];
const achievements = achievementsRaw as AchievementDef[];
const habitats = habitatsRaw as HabitatDef[];
const trinkets = trinketsRaw as TrinketDef[];
const sprites = spritesRaw as SpriteDef[];

export const contentPackV1: ContentPack = {
  version: 1,
  models,
  species,
  traits,
  patterns,
  achievements,
  habitats,
  trinkets,
  sprites,
  dexTotal: 112,
};

// ---------------------------------------------------------------------------
// Pack validator
// ---------------------------------------------------------------------------

/**
 * Validates a ContentPack for internal consistency.
 * Returns an array of error strings; an empty array means the pack is valid.
 */
export function validatePack(pack: ContentPack): string[] {
  const errors: string[] = [];

  const spriteIds = new Set(pack.sprites.map((s) => s.id));
  const speciesIds = new Set(pack.species.map((s) => s.id));
  const habitatIds = new Set(pack.habitats.map((h) => h.id));
  const trinketIds = new Set(pack.trinkets.map((t) => t.id));

  // --- Duplicate species ids ---
  const seenSpeciesIds = new Set<string>();
  const seenSpeciesNums = new Set<number>();
  for (const sp of pack.species) {
    if (seenSpeciesIds.has(sp.id)) errors.push(`Duplicate species id: ${sp.id}`);
    seenSpeciesIds.add(sp.id);
    if (seenSpeciesNums.has(sp.num))
      errors.push(`Duplicate species num: ${sp.num} (species ${sp.id})`);
    seenSpeciesNums.add(sp.num);
  }

  // --- Duplicate habitat ids ---
  const seenHabitatIds = new Set<string>();
  for (const h of pack.habitats) {
    if (seenHabitatIds.has(h.id)) errors.push(`Duplicate habitat id: ${h.id}`);
    seenHabitatIds.add(h.id);
  }

  // --- Duplicate trinket ids ---
  const seenTrinketIds = new Set<string>();
  for (const t of pack.trinkets) {
    if (seenTrinketIds.has(t.id)) errors.push(`Duplicate trinket id: ${t.id}`);
    seenTrinketIds.add(t.id);
  }

  // --- Duplicate sprite ids ---
  const seenSpriteIds = new Set<string>();
  for (const s of pack.sprites) {
    if (seenSpriteIds.has(s.id)) errors.push(`Duplicate sprite id: ${s.id}`);
    seenSpriteIds.add(s.id);
  }

  // --- Duplicate achievement ids ---
  const seenAchievIds = new Set<string>();
  for (const a of pack.achievements) {
    if (seenAchievIds.has(a.id)) errors.push(`Duplicate achievement id: ${a.id}`);
    seenAchievIds.add(a.id);
  }

  // --- Species sprite refs ---
  for (const sp of pack.species) {
    if (!spriteIds.has(sp.spriteId)) {
      errors.push(`Species ${sp.id} references unknown spriteId: ${sp.spriteId}`);
    }
  }

  // --- Species evolvesTo targets exist ---
  for (const sp of pack.species) {
    for (const branch of sp.evolvesTo) {
      if (!speciesIds.has(branch.species)) {
        errors.push(`Species ${sp.id} evolvesTo unknown species: ${branch.species}`);
      }
    }
  }

  // --- Each non-apex species must have a 'default' branch ---
  for (const sp of pack.species) {
    if (sp.evolvesTo.length > 0) {
      const hasDefault = sp.evolvesTo.some((b) => b.when.kind === 'default');
      if (!hasDefault) {
        errors.push(`Species ${sp.id} has evolvesTo branches but no 'default' branch`);
      }
    }
  }

  // --- Habitat sprite refs ---
  for (const h of pack.habitats) {
    if (!spriteIds.has(h.spriteId)) {
      errors.push(`Habitat ${h.id} references unknown spriteId: ${h.spriteId}`);
    }
  }

  // --- Trinket sprite refs ---
  for (const t of pack.trinkets) {
    if (!spriteIds.has(t.spriteId)) {
      errors.push(`Trinket ${t.id} references unknown spriteId: ${t.spriteId}`);
    }
  }

  // --- Achievement rewards reference existing ids ---
  for (const a of pack.achievements) {
    if (a.reward) {
      if (a.reward.kind === 'habitat' && !habitatIds.has(a.reward.id)) {
        errors.push(`Achievement ${a.id} rewards unknown habitat: ${a.reward.id}`);
      }
      if (a.reward.kind === 'trinket' && !trinketIds.has(a.reward.id)) {
        errors.push(`Achievement ${a.id} rewards unknown trinket: ${a.reward.id}`);
      }
    }
  }

  // --- Equal stat budget per stage ---
  // Group species by stage, compute sum for each, verify all equal within a stage.
  const stageGroups = new Map<string, number[]>();
  for (const sp of pack.species) {
    const total = sp.statWeights.pwr + sp.statWeights.spd + sp.statWeights.wis + sp.statWeights.grt;
    const list = stageGroups.get(sp.stage) ?? [];
    list.push(total);
    stageGroups.set(sp.stage, list);
  }
  for (const [stage, totals] of stageGroups) {
    const first = totals[0];
    if (first === undefined) continue;
    for (const t of totals) {
      if (t !== first) {
        errors.push(`Unequal stat budget in stage '${stage}': expected ${first} but found ${t}`);
      }
    }
  }

  // --- Model rules: no duplicate patterns ---
  const seenPatterns = new Set<string>();
  for (const m of pack.models) {
    if (seenPatterns.has(m.pattern)) errors.push(`Duplicate model pattern: ${m.pattern}`);
    seenPatterns.add(m.pattern);
  }

  return errors;
}

// ---------------------------------------------------------------------------
// Model resolution helper (exported for consumers + tests)
// ---------------------------------------------------------------------------

/**
 * Resolve a raw model id to a house using the pack's ordered model rules.
 * Returns 'wild' if no rule matches (dormant gene).
 */
export function resolveHouse(
  modelId: string,
  models: ModelRule[],
): 'aether' | 'cipher' | 'flux' | 'forge' | 'wild' {
  for (const rule of models) {
    if (matchesGlob(modelId, rule.pattern)) {
      return rule.house;
    }
  }
  return 'wild';
}

/** Simple glob match: only '*' wildcard supported (matches any sequence of chars). */
function matchesGlob(input: string, pattern: string): boolean {
  // Escape regex special chars except '*', then replace '*' with '.*'
  const re = new RegExp(
    '^' + pattern.replace(/[.+?^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '.*') + '$',
  );
  return re.test(input);
}
