/**
 * Token Tamers v1 starter content pack.
 *
 * Sprite generation approach: all sprites in sprites.json are deterministically
 * generated by packages/content/tools/gen-sprites.ts using a seeded LCG keyed on
 * each sprite id. The script is committed alongside the output so sprites.json can
 * be regenerated at any time with `pnpm tsx packages/content/tools/gen-sprites.ts`.
 * TODO art pass: replace placeholder grids with hand-crafted sprites before release.
 *
 * JSON files are imported statically (resolveJsonModule: true) so the bundle
 * embeds all content — zero runtime file reads needed.
 */
import type {
  ContentPack,
  ModelRule,
  SpeciesDef,
  TraitDef,
  PatternDef,
  AchievementDef,
  HabitatDef,
  TrinketDef,
  SpriteDef,
} from '@token-tamers/core';

import modelsRaw from '../content/v1/models.json' with { type: 'json' };
import speciesRaw from '../content/v1/species.json' with { type: 'json' };
import traitsRaw from '../content/v1/traits.json' with { type: 'json' };
import patternsRaw from '../content/v1/patterns.json' with { type: 'json' };
import achievementsRaw from '../content/v1/achievements.json' with { type: 'json' };
import habitatsRaw from '../content/v1/habitats.json' with { type: 'json' };
import trinketsRaw from '../content/v1/trinkets.json' with { type: 'json' };
import spritesRaw from '../content/v1/sprites.json' with { type: 'json' };

const models = modelsRaw as ModelRule[];
const species = speciesRaw as SpeciesDef[];
const traits = traitsRaw as TraitDef[];
const patterns = patternsRaw as PatternDef[];
const achievements = achievementsRaw as AchievementDef[];
const habitats = habitatsRaw as HabitatDef[];
const trinkets = trinketsRaw as TrinketDef[];
const sprites = spritesRaw as SpriteDef[];

export const contentPackV1: ContentPack = {
  version: 1,
  models,
  species,
  traits,
  patterns,
  achievements,
  habitats,
  trinkets,
  sprites,
  dexTotal: 112,
};

export { validatePack } from './validate';
export { resolveHouse } from './models';
